### ISSUE TITLE
sponsor coded value domain

### ISSUE THREAD

**Issue by steveoh** [agrc/plpco-rdcc-notifications#10]
The coded value domains for the sponsor field are from 1-41 but there are many records with values over 100. Please sort out this data issue with the client and what the behavior should be for the items outside the domain.

**Comment by nathankota** [comment]
related to #6

**Comment by nathankota** [comment]
Client is aware and working on fixing the data.

**Comment by jwolfski** [comment]
> The coded value domains for the sponsor field are from 1-41 but there are many records with values over 100. Please sort out this data issue with the client and what the behavior should be for the items outside the domain.

I recalculated all the records that were outside the domain list. Should be good now.
