### ISSUE TITLE
new project query returning almost every record

### ISSUE THREAD

**Issue by steveoh** [agrc/plpco-rdcc-notifications#11]
there is a data issue with the created date that should to be fixed. But it also brings up a good question of should we limit the number of projects returned from a query to something below the default 2000.

**Comment by nathankota** [comment]
The data issue was a result of a bulk data transfer that set all of the `created_date` values to the transfer date (2021/10/29). Jason is aware of the issue, and is strategizing a solution, possibly by adding another data field to the schema for a date that he can edit through his dashboard or survey123 app (there is some restriction on editing `created_date`). If the new field is implemented he might request to have the email query point at it. For now, he is good with this query and understands the implications of bulk imports making all of the `created_date` values the same. If another bulk transfer is done, after a week has passed the data included in the email will normalize back to only the projects actually submitted in the previous week, so there is not an immediate need to limit the number of projects returned.

**Comment by steveoh** [comment]
You can calc a field based on create date, remove editor tracking, fix the issues, and re enable editor tracking pointing it at the corrected date field.
