### ISSUE TITLE
State Comments section of email

### ISSUE THREAD

**Issue by nathankota** [agrc/plpco-rdcc-notifications#13]
### Table
[State_Comments](https://maps.publiclands.utah.gov/server/rest/services/RDCC/RDCC_Project/FeatureServer/4)

### Relationship

> 1:M using GlobalID on RDCC Project Layer and RelGlobalID on the State_Comment Table

### Included in email:

**State Comment(s) Published** (section heading)
&nbsp;&nbsp;&nbsp;&nbsp; **Project #** ProjectID - project_abstract
&nbsp;&nbsp;&nbsp;&nbsp; **Sponsor:** `sponsor`

**Comment by nathankota** [comment]
![image](https://user-images.githubusercontent.com/15659642/139960144-747eb69c-ea94-4243-9aef-1818f064041d.png)

**Comment by nathankota** [comment]
"Download State Comment(s)..."  line and link removed b/c there is no longer a way to link directly to individual projects on the new RDCC dashboard.

**Comment by steveoh** [comment]
That query doesn't have a filter and would get every record. What is the filtering criteria?

**Comment by steveoh** [comment]
I am not understanding the database model.

![image](https://user-images.githubusercontent.com/325813/139967365-c41a874d-121b-4508-9476-c02ee6c4feb5.png)

It only looks like a 1:M lookup table. Do I need to traverse into another table for any information? Or am I simply querying all the data in this table and showing the projects and there is some other process that manages the records?

The hibernate code references uploadDate and attachments. Do those need to be involved?

```sql
SELECT p from Project p where p.id in (SELECT distinct p2.id from Project p2 join p2.attachments as att where att.uploadDate > [7 days ago] and att.uploadDate < [today]);
```

**Comment by steveoh** [comment]
I spoke to jason and he mentioned using the status of 

```json
{
"name": "State Comment Published",
"code": "7"
}```

along with the `last_edited_date ` field.

I'm going to code this up for the time range of today minus 7 days for the time being.

**Comment by nathankota** [comment]
Validated with client, including

> I'm going to code this up for the time range of today minus 7 days for the time being.

Any changes to this email section will be tracked in separate issue(s).
