### ISSUE TITLE
Determine time zone feature service dates are stored as

### ISSUE THREAD

**Issue by steveoh** [agrc/plpco-rdcc-notifications#19]
this will affect parsing the date and could cause off by one issues depending on time zone.

**Comment by nathankota** [comment]
Jason said date fields are stored as MST.

**Comment by nathankota** [comment]
Jason is _mostly_ confident that he selected MST when he published the service. He said he would republish again to make sure.

**Comment by jwolfski** [comment]
I have confirmed that the RDCC Project Feature service is MST on our Server Manager. Adjusted for Daylight Savings as well

**Comment by steveoh** [comment]
the query endpoint returns times in UTC. i think we should be good as it appears the db does not have a timezone selected
