### ISSUE TITLE
State comment dates

### ISSUE THREAD

**Issue by steveoh** [agrc/plpco-rdcc-notifications#24]
state comments published section should be filtered to just show state comments published that previous week.

**Comment by steveoh** [comment]
```js
const featureSet = await logQuery('0/query', {
    f: 'json',
    where: `(last_edited_date BETWEEN TIMESTAMP '${getBeginningOfLastWeek(
      new Date()
    )}' AND TIMESTAMP '${getEndOfLastWeek(new Date())}') AND status='7'`,
    outFields: 'ProjectID,sponsor,title_action',
    orderByFields: 'last_edited_date DESC',
    returnGeometry: false,
    resultRecordCount: maxRecordCount,
  });
```

It appears the state comments published are already using a weeks worth of queries. @jwolfski Can you verify that the data matches what you are expecting? What items showed up that you didn't think should be there?

**Comment by steveoh** [comment]
@jwolfski, hey another email went out. Is this query for state comments still returning incorrect data? If it is, would you please generate the correct query and share the parameters you used so we can get it right in the code? Thanks! Looking forward to pushing this to production.

**Comment by jwolfski** [comment]
The the only change I see is THis part "

   - *New Projects
   <https://mail.google.com/mail/u/0/#m_1994852813442397036_new-projects>*:
   Projects approved by PLPCO last week"

Needs to change to "*New Projects
<https://mail.google.com/mail/u/0/#m_3794521996413532563_new-projects>*:
Projects submitted to the RDCC"

**Comment by steveoh** [comment]
@jwolfski, you are referring to https://github.com/agrc/plpco-rdcc-notifications/issues/23 which we haven't completed yet?

 Are you saying that the original issue you brought up for this issue is no longer an issue?

**Comment by jwolfski** [comment]
Sorry, you are correct i am referring to Issue #23. 
Issue #24 is self resolved. Looks good on my end.
