### ISSUE TITLE
Generate Weekly Email

### ISSUE THREAD

**Issue by stdavis** [agrc/plpco-rdcc-notifications#3]
[Here's an example of one](https://docs.google.com/document/d/13cNzc_QP-SkhjSbfpMpk21Llj1XOjxtQqNNesC1gf6A/edit?usp=sharing)

**Comment by nathankota** [comment]
https://docs.google.com/document/d/1AR9KfYyMMYKpivs3BMdHVI1YIQyHOZb8uAgBDG0fUfo/edit?pli=1

**Comment by steveoh** [comment]
i have a dynamic template in sendgrid for the email sending `d-88160054084447e8b391dd171971424c`

**Comment by nathankota** [comment]
The dev email adheres to the sections, data, and layout defined in the doc and otherwise communicated from PLPCO so far. Any changes will be documented in separate tasks/issues.
