### ISSUE TITLE
Query RDCC feature service for information to include in the email

### ISSUE THREAD

**Issue by nathankota** [agrc/plpco-rdcc-notifications#4]
Service: https://maps.publiclands.utah.gov/server/rest/services/RDCC/RDCC_Project/FeatureServer

Three sections of the email:

1. New Projects
2. Upcoming Dates
3. State Comment(s) Published

Notes about what to include in the email [here](https://docs.google.com/document/d/1AR9KfYyMMYKpivs3BMdHVI1YIQyHOZb8uAgBDG0fUfo/edit).

**Comment by steveoh** [comment]
This issue is an epic. I'm going to close it in favor of the more detailed issues.
