### ISSUE TITLE
New Projects section of email

### ISSUE THREAD

**Issue by nathankota** [agrc/plpco-rdcc-notifications#6]
#### Layer
[RDCC Project](https://maps.publiclands.utah.gov/server/rest/services/RDCC/RDCC_Project/FeatureServer/0)

#### Query

> `SELECT (the following attributes) From RDCC Project WHERE created_date BETWEEN  [today] AND [today-7]`

**Note: **`created_date` stored as MST time zone

#### Included in email:

**New Projects** (section heading)

**Project #** `ProjectID` - `project_abstract`
&nbsp;&nbsp;&nbsp;&nbsp; **Sponsor:** `sponsor`
&nbsp;&nbsp;&nbsp;&nbsp; **Comment Deadline:** `comment_deadline`
&nbsp;&nbsp;&nbsp;&nbsp; **Counties:** `county`

**Comment by nathankota** [comment]
The layout in the existing email looks like:

![image](https://user-images.githubusercontent.com/15659642/139904808-c8614d18-98a4-47bc-9376-2ec86ddd8b1c.png)

**Comment by steveoh** [comment]
I'm seeing creation dates in the future. Is that normal? Do we want to limit the number somehow?

**Comment by nathankota** [comment]
I gathered the date range logic from the hibernate logic that was sent, but it doesn't look right now...like it wouldn't exclude any results.

**Comment by nathankota** [comment]
not proper sql, but I changed the range in the initial comment. It is intended to only capture projects with `created-date` within the past 7 days of the email being sent.

**Comment by steveoh** [comment]
there are over 2000 results for this query

**Comment by nathankota** [comment]
2k+ within the past week?

**Comment by nathankota** [comment]
The week query is good, but there was a recent bulk upload that caused a large sum of records to have a `created_date` within the last week, which is skewing the results. After November 5th, the query results will normalize.

**Comment by nathankota** [comment]
"View Full Project" link removed b/c there is no longer a way to link directly to individual projects on the new RDCC dashboard.

**Comment by nathankota** [comment]
Validated with client. Any changes to this email section will be tracked in separate issue(s).
