### ISSUE TITLE
Weekly email intro text

### ISSUE THREAD

**Issue by nathankota** [agrc/plpco-rdcc-notifications#7]
The following text is included at the top of the body of each weekly email:

> Here is the RDCC notice for this week. 
> This notice includes the following sections:
>   New Projects: Projects approved by PLPCO last week
>   Upcoming Dates: Projects with comment deadlines next week
>   State Comment(s) Published: Projects in which state comments were published last week.
> 
> For more project information, search for a specific project number at [rdcc.utah.gov](rdcc.utah.gov) 
> For questions please email us at rdcc@utah.gov.

**Comment by nathankota** [comment]
The second-to-last line of text was added late yesterday afternoon and edited slightly this morning, and should be included...

> For more project information, search for a specific project number at rdcc.utah.gov

**Comment by steveoh** [comment]
Is the search something we can link to?

**Comment by nathankota** [comment]
This looks good. We cannot link directly to the search in the Esri dashboard.
