### ISSUE TITLE
Weekly email subject line

### ISSUE THREAD

**Issue by nathankota** [agrc/plpco-rdcc-notifications#8]
> RDCC Notice for `[today's date]`

**Comment by steveoh** [comment]
https://support.sendgrid.com/hc/en-us/articles/1260802535110-Create-a-Dynamic-Email-Subject-Line-with-Mustache-Templates

**Comment by steveoh** [comment]
today's date is nebulous. Would you provide a format? I'll use yyyy/MM/dd for the time being.

**Comment by nathankota** [comment]
The date format for the current system's email is as follows. We can replicate it. 

![image](https://user-images.githubusercontent.com/15659642/141003292-011a1674-3b95-446c-a816-f17b62b27f24.png)

**Comment by nathankota** [comment]
looks good!
