### ISSUE TITLE
Weekly email schedule

### ISSUE THREAD

**Issue by nathankota** [agrc/plpco-rdcc-notifications#9]
set email function to run at 5:00 a.m. on Monday mornings in our time zone

**Comment by nathankota** [comment]
Email not received Monday, November 15th

**Comment by steveoh** [comment]
I reverted the experimental security code. We should get an email as long as the service doesn't change it's sharing. which it should. I will look into setting up an alert to notify us that it failed.

**Comment by nathankota** [comment]
@steveoh do you agree that this issue can be closed as it stands? Perhaps a new issue to track the security of the service is also in order?

**Comment by steveoh** [comment]
yeah i'm good with that now that the alerting is set up
